default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: admin
  host: localhost
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hello_rails_react
  username: postgres
  password: admin
  host: localhost
  port: 5432

test:
  <<: *default
  database: hello_rails_react_test

production:
  <<: *default
  database: hello_rails_react_production
  username: postgres
  password: admin